//
//  SignUPConfigurator.swift
//  iosSkillstest
//
//  Created by Everton Miranda Vitório on 21/09/18.
//  Copyright (c) 2018 Everton Miranda Vitório. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension SignUPInteractor: SignUPViewControllerOutput, SignUPRouterDataSource, SignUPRouterDataDestination {
}

extension SignUPPresenter: SignUPInteractorOutput {
}

class SignUPConfigurator {
    // MARK: Object lifecycle

    static let sharedInstance = SignUPConfigurator()

    private init() {}

    // MARK: Configuration

    func configure(viewController: SignUPViewController) {

        let presenter = SignUPPresenter()
        presenter.output = viewController

        let interactor = SignUPInteractor()
        interactor.output = presenter

        let router = SignUPRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)

        viewController.output = interactor
        viewController.router = router
    }
}
