//
//  SignUPInteractor.swift
//  iosSkillstest
//
//  Created by Everton Miranda Vitório on 21/09/18.
//  Copyright (c) 2018 Everton Miranda Vitório. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import RealmSwift

protocol SignUPInteractorInput {
    func singUPUser(request: SignUPScene.SignUP.Request)
}

protocol SignUPInteractorOutput {
    func presentSignUP(reponse: SignUPScene.SignUP.Response)
}

protocol SignUPDataSource {
    
}

protocol SignUPDataDestination {
    
}

class SignUPInteractor: SignUPInteractorInput, SignUPDataSource, SignUPDataDestination {
    
    var output: SignUPInteractorOutput?
    
    // MARK: Business logic
    
    func singUPUser(request: SignUPScene.SignUP.Request) {
        let user = User()
        user.name = request.name
        user.email = request.email.lowercased()
        user.password = request.password
        var state = SignUPScene.SignUP.Response.State.failure(errorMessage: "Erro ao cadastrar usuario")
        do {
            let realm = try Realm(configuration: .defaultConfiguration)
            try realm.write {
                realm.add(user)
            }
            state = SignUPScene.SignUP.Response.State.sucess(message: "Usuario cadastrado com sucesso!")
        } catch {
            print(error)
        }
        let response = SignUPScene.SignUP.Response(state: state)
        output?.presentSignUP(reponse: response)
    }
}
