excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

disabled_rules: # rule identifiers to exclude from running
  - nesting

line_length: 180

identifier_name:
  excluded: # excluded via string array
    - id
