//
//  LoginPresenter.swift
//  iosSkillstest
//
//  Created by Everton Miranda Vitório on 22/09/18.
//  Copyright (c) 2018 Everton Miranda Vitório. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol LoginPresenterInput {
    func presentLogin(response: LoginScene.Login.Response)
}

protocol LoginPresenterOutput: class {
    func displaySucessLogin(viewModel: LoginScene.Login.ViewModel)
    func displayFailureLogin(viewModel: LoginScene.Login.ViewModel)
}

class LoginPresenter: LoginPresenterInput {
    
    weak var output: LoginPresenterOutput?
    
    // MARK: Presentation logic
    
    func presentLogin(response: LoginScene.Login.Response) {
        switch response.state {
        case .sucess(message: let message):
            let viewModel = LoginScene.Login.ViewModel(message: message)
            output?.displaySucessLogin(viewModel: viewModel)
        case .failure(errorMessage: let message):
            let viewModel = LoginScene.Login.ViewModel(message: message)
            output?.displayFailureLogin(viewModel: viewModel)
        }
    }
}
