//
//  LoginModels.swift
//  iosSkillstest
//
//  Created by Everton Miranda Vitório on 22/09/18.
//  Copyright (c) 2018 Everton Miranda Vitório. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
//
//  Type "usecase" for some magic!

struct LoginScene {

    struct Login {

        struct Request {
            let email: String
            let password: String
        }

        struct Response {
            enum State {
                case sucess(message: String)
                case failure(errorMessage: String)
            }
            let state: State
        }

        struct ViewModel {
            let message: String
        }
    }
}
