//
//  LoginInteractor.swift
//  iosSkillstest
//
//  Created by Everton Miranda Vitório on 22/09/18.
//  Copyright (c) 2018 Everton Miranda Vitório. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import RealmSwift

protocol LoginInteractorInput {
    func login(request: LoginScene.Login.Request)
}

protocol LoginInteractorOutput {
    func presentLogin(response: LoginScene.Login.Response)
}

protocol LoginDataSource {
    var logedUser: User? { get }
}

protocol LoginDataDestination {
}

class LoginInteractor: LoginInteractorInput, LoginDataSource, LoginDataDestination {

    var output: LoginInteractorOutput?

    var logedUser: User?

    // MARK: Business logic

    func login(request: LoginScene.Login.Request) {
        var state = LoginScene.Login.Response.State.failure(errorMessage: "Erro ao logar usuario")
        do {
            let realm = try Realm()
            let validateUser = realm.objects(User.self).filter { user in
                return user.email.lowercased() == request.email.lowercased() && user.password == request.password
            }.first
            if let user = validateUser {
                logedUser = user
                state = .sucess(message: "Usuario logado com sucesso")
            } else {
                state = .failure(errorMessage: "Email ou senha não estão corretos")
            }
        } catch { }
        let response = LoginScene.Login.Response(state: state)
        output?.presentLogin(response: response)
    }
}
