//
//  UsersInteractor.swift
//  iosSkillstest
//
//  Created by Everton Miranda Vitório on 22/09/18.
//  Copyright (c) 2018 Everton Miranda Vitório. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol UsersInteractorInput {
    
}

protocol UsersInteractorOutput {
    
}

protocol UsersDataSource {
    
}

protocol UsersDataDestination {
    var user: User! { get set }
}

class UsersInteractor: UsersInteractorInput, UsersDataSource, UsersDataDestination {
    
    
    
    var output: UsersInteractorOutput?
    var user: User!
    
    // MARK: Business logic
    

}
