//
//  UsersPresenter.swift
//  iosSkillstest
//
//  Created by Everton Miranda Vitório on 22/09/18.
//  Copyright (c) 2018 Everton Miranda Vitório. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol UsersPresenterInput {
    
}

protocol UsersPresenterOutput: class {
    
}

class UsersPresenter: UsersPresenterInput {
    
    weak var output: UsersPresenterOutput?
    
    // MARK: Presentation logic
    
}
