//
//  UsersRouter.swift
//  iosSkillstest
//
//  Created by Everton Miranda Vitório on 22/09/18.
//  Copyright (c) 2018 Everton Miranda Vitório. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol UsersRouterInput {

}

protocol UsersRouterDataSource: class {
    var editUser: User? { get }
}

protocol UsersRouterDataDestination: class {
    var user: User! { get set }
}

class UsersRouter: UsersRouterInput {

    struct SegueIdentifiers {
        static let addUserSegue = "AddUserSegue"
    }

    var user: User!

    weak var viewController: UsersViewController!
    weak private var dataSource: UsersRouterDataSource!
    weak var dataDestination: UsersRouterDataDestination!

    init(viewController: UsersViewController, dataSource: UsersRouterDataSource, dataDestination: UsersRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }

    // MARK: Navigation

    func navigateToSignUpScene() {

        viewController.performSegue(withIdentifier: SegueIdentifiers.addUserSegue, sender: self)
    }

    // MARK: Communication

    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        switch segue.identifier {
        case SegueIdentifiers.addUserSegue:
            passDataSignUpScene(for: segue)
            return
        default:
            return
        }
    }

    func passDataSignUpScene(for segue: UIStoryboardSegue) {
        if let signUpVC = segue.destination as? SignUPViewController {
            if let user = dataSource.editUser {
                signUpVC.router?.dataDestination.editUser = user
            }
        }
    }
}
