//
//  AlbunsPresenter.swift
//  iosSkillstest
//
//  Created by Everton Miranda Vitório on 22/09/18.
//  Copyright (c) 2018 Everton Miranda Vitório. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol AlbunsPresenterInput {
    
}

protocol AlbunsPresenterOutput: class {
    
}

class AlbunsPresenter: AlbunsPresenterInput {
    
    weak var output: AlbunsPresenterOutput?
    
    // MARK: Presentation logic
    
}
