//
//  AlbunsModels.swift
//  iosSkillstest
//
//  Created by Everton Miranda Vitório on 22/09/18.
//  Copyright (c) 2018 Everton Miranda Vitório. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
//
//  Type "usecase" for some magic!

import Result

struct AlbunsScene {

    struct FetchAlbuns {

        struct Request { }

        struct Response {

            enum State {
                case sucess([Album])
                case failure(errorMessage: String)
            }
            let state: State
        }

        struct ViewModel {

            struct AlbumRow {
                let title: String
                let photoURL: String
            }

            let albumRows: [AlbumRow]
        }
    }
}
