//
//  AlbunsConfigurator.swift
//  iosSkillstest
//
//  Created by Everton Miranda Vitório on 22/09/18.
//  Copyright (c) 2018 Everton Miranda Vitório. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension AlbunsInteractor: AlbunsViewControllerOutput, AlbunsRouterDataSource, AlbunsRouterDataDestination {
}

extension AlbunsPresenter: AlbunsInteractorOutput {
}

class AlbunsConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = AlbunsConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: AlbunsViewController) {
        
        let presenter = AlbunsPresenter()
        presenter.output = viewController
        
        let interactor = AlbunsInteractor()
        interactor.output = presenter
        
        let router = AlbunsRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
