//
//  TabBarViewController.swift
//  iosSkillstest
//
//  Created by Everton Miranda Vitório on 22/09/18.
//  Copyright (c) 2018 Everton Miranda Vitório. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol TabBarViewControllerInput {

}

protocol TabBarViewControllerOutput {

}

class TabBarViewController: UITabBarController, TabBarViewControllerInput {

    var output: TabBarViewControllerOutput?
    var router: TabBarRouter?

    // MARK: Object lifecycle

    override func awakeFromNib() {
        super.awakeFromNib()
        TabBarConfigurator.sharedInstance.configure(viewController: self)
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        router?.passDataToUsersVC()

    }

    // MARK: Requests

    // MARK: Display logic

}

//This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension TabBarViewController: TabBarPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router?.passDataToNextScene(for: segue)
    }
}
