//
//  TabBarInteractor.swift
//  iosSkillstest
//
//  Created by Everton Miranda Vitório on 22/09/18.
//  Copyright (c) 2018 Everton Miranda Vitório. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol TabBarInteractorInput {
    
}

protocol TabBarInteractorOutput {
    
}

protocol TabBarDataSource {
    
}

protocol TabBarDataDestination {
    var user: User! { get set }
}

class TabBarInteractor: TabBarInteractorInput, TabBarDataSource, TabBarDataDestination {
    var user: User!
    
    
    var output: TabBarInteractorOutput?
    
    // MARK: Business logic
    

}
