//
//  TabBarConfigurator.swift
//  iosSkillstest
//
//  Created by Everton Miranda Vitório on 22/09/18.
//  Copyright (c) 2018 Everton Miranda Vitório. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension TabBarInteractor: TabBarViewControllerOutput, TabBarRouterDataSource, TabBarRouterDataDestination {
}

extension TabBarPresenter: TabBarInteractorOutput {
}

class TabBarConfigurator {
    // MARK: Object lifecycle

    static let sharedInstance = TabBarConfigurator()

    private init() {}

    // MARK: Configuration

    func configure(viewController: TabBarViewController) {

        let presenter = TabBarPresenter()
        presenter.output = viewController

        let interactor = TabBarInteractor()
        interactor.output = presenter

        let router = TabBarRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)

        viewController.output = interactor
        viewController.router = router
    }
}
